language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

env:
  global:
    - COMPOSER_ARGS="--no-interaction --no-progress --no-suggest"

cache:
  directories:
    - $HOME/.composer/cache

install:
  travis_retry composer update $COMPOSER_ARGS

script:
  - composer test
  - composer phpcs
  - composer phpstan
